plugins:
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    # Because we're not using the default filename `.eslintrc.js`
    config:
      config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_paths:
- src/utilities/__tests__/**
- src/assets/scss/addons/**
- src/assets/scss/components/**
- src/assets/scss/core/**
- src/assets/scss/free/**
- src/assets/scss/theme/**
- src/assets/scss/mdb.scss
- features/**
