plugins:
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    # Because we're not using the default filename `.eslintrc.js`
    config:
      config: .eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_paths:
- src/utilities/__tests__/**
- features/**
