language: node_js
node_js:
  - 'node'
  - 'lts/*'
sudo: false
install:
  - yarn install
script:
  - scss-lint
  - eslint
  - yarn test
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
