---
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.14.1
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  build:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: circleci/node:10.14.1
    environment:
      REACT_APP_HOST: https://family.services.govt.nz/
      REACT_APP_GH_PAGES_SUFFIX: /
      REACT_APP_ADDRESS_FINDER_API_KEY: XU3BTFEQHKV9NY8AWDMG
      REACT_APP_API_PATH: https://catalogue.data.govt.nz/api/3/action/
      REACT_APP_API_RESOURCE_ID: 35de6bf8-b254-4025-89f5-da9eb6adf9a0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "57:d9:4d:8a:b2:8a:0a:99:55:49:98:66:23:5a:e0:cd"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: git config --global user.email "labplus@dia.govt.nz"
      - run: git config --global user.name "Lab Plus"
      - run: npm install
      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2
  test-and-build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
