---
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

branches:
  ignore:
    - gh-pages

jobs:
  test:
    docker:
      - image: circleci/node:9.11.2
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

  build:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: yarn build

  deploy:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "58:26:32:54:2a:7f:c1:29:52:4b:ba:00:2c:62:24:38"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: git config --global user.email "labplus@dia.govt.nz"
      - run: git config --global user.name "Lab Plus"
      - run: yarn install
      - run: yarn build
      - run: yarn deploy

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
